import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "@/contexts/UserContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
            src="https://telegram.org/js/telegram-web-app.js"
            async
        ></script>
      </head>
      <body className="bg-gradient-to-b from-[#0F1722] to-[#4D818C] font-teko tracking-wide h-screen w-screen">
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}